export const COLORS = {
  PRIMARY: "#F37165",
  SECONDARY: "#FEF2F1",
  SUCCESS: "#0A84FF",
  ERROR: "#FF453A",
  BORDER: "#ECECEC",
  FOCUSED_BORDER: "#757575",
  DISABLED_BORDER: "#ECECEC",
  DISABLED_BG: "#F8F8F8",
  PLACEHOLDER: "#BDBDBD",
  DISABLED_TEXT: "#DDDDDD",
  LABEL: "#6B7280",
}
